version: '3'
services:
  schoolapp:
    build: .
    user: "${UID}:${GID}"
    volumes:
    - ./:/var/www
    depends_on:
      - schoolapp-mysql

  schoolapp-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: schoolapp
      MYSQL_ROOT_PASSWORD: root

  schoolapp-nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - schoolapp
